### ISSUE TITLE
Implement `From<Vec<bool>>` and `Into<Vec<bool>>`

### ISSUE THREAD

**Issue by venkatarun95** [marcianx/bitvec-rs#1]
Does it make sense to implement `From<Vec<bool>>` and `Into<Vec<bool>>` to allow easy conversion between `BitVec` and `Vec<bool>`?

**Comment by marcianx** [comment]
Sure, if there's a need. Is this something you run across regularly? Curious because that conversation does an expensive increase in size; so I would expect folks would typically find a way to directly initialize it (vs `From`) or use an iterator on `bool` (vs `Into`).

**Comment by venkatarun95** [comment]
The use-case is when you have to inter-operate with code that uses `Vec<bool>`. You are right that it is probably better to create an iterator on `bool` (and `collect` it, if necessary) than use `Into`

But I feel there is a use-case for `From<Vec<bool>>` (which is what I ran into). In this case, there is a decrease in size.

We could use `Extend` instead of `From`, but if the goal is to just convert from `Vec<bool>` to `BitVec`, then `From` is more natural (and less verbose), since we aren't really extending.

**Comment by marcianx** [comment]
Ok, if that use-case is a need, I'll add it in.

**Comment by marcianx** [comment]
This is done, and published as v0.1.2. See the new `CHANGELOG.md` for all the changes. Let me know if you run into any issues.

It does, however, bring up an awkward situation where the existing `into_vec` becomes ambiguous. I [opened up a thread](https://users.rust-lang.org/t/naming-convention-to-distinguish-conversion-to-vec-bool-vs-vec-u8/27597) to figure out the naming convention and then I'll probably make a backward-incompatible change and push another version, bumping up the minor version.

In any case, this issue is fixed.

**Comment by marcianx** [comment]
Just FYI: I changed the API a little bit based on feedback in the thread and bumped up the version to `0.2.0`. See the `CHANGELOG.md` for recent updates.
